---
server: server
port: 6697
ssl: true
defaultChannels:
    - "#OctobotTest"
    - "#lobby"
nick: octoBot
password: pass1234
logging:
    logFile: log.txt
    verboseLogFile: verbose.txt
    maxLogSize: 2097152 # in bytes  (2KiB default)
    maxVerboseLogSize: 5242880 # In bytes (5KiB default)
commands:
    commandPrefix: "!" # MUST be a single character for compatibility with some poorly written modules
