---
server: irc.horse
port: 6697
defaultChannels:
    - "#Sleu"
    #- "#TwilightsCastle"
nick: sleumasBot
password: Rarity01
logging:
    logFile: log.txt
    verboseLogFile: verbose.txt
    maxLogSize: 2097152 # in bytes  (2KiB default)
    maxVerboseLogSize: 5242880 # In bytes (5KiB default)
commands:
    commandPrefix: "|" # MUST be a single character for compatibility with some modules